import './globals.css'
import Link from "next/link";

export const metadata = {
  title: 'MSA Study',
  description: 'Generated by JaeHong Min',
}

export default function RootLayout({children}) {
  return (
    <html>
      <body>
        <nav className="navbar">
          <Link href="/">홈</Link>
          <Link href="/list">List</Link>
          <Link href="/create">상품 추가</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
